### ISSUE TITLE
Incompatible units in navbar.scss 

### ISSUE THREAD

**Issue by nelsonmariano** [mjonuschat/bootstrap-sass-rails#51] opened 2013-07-01 14:58 UTC
Hi there,
I imported Bootstrap navbar in my rails project (doing: @import "twitter/bootstrap/navbar";) and after that I got this message:

Error Compilling CSS asset
Sass::UnitConversionError: Incompatible units: 'em' and 'px'.

And it says the error is in ../stylesheets/twitter/bootstrap/_navbar.scss:53
Which means the following statement:

padding: (($navbarHeight - $baseLineHeight) / 2) 20px (($navbarHeight - $baseLineHeight) / 2);

I put this statement in my own scss and I got the same error, the error is exactly in the subtraction: $navbarHeight - $baseLineHeight, but if I put, for example, "40px - 20px", there is no error. And I checked the file _variables.scss and both variables have correct values, i. e., in pixels.

So, any ideia what it can be? I don't know if it's some configuration problems or something, I have been using sass Bootstrap here with no problems.

Thanks a million..

**Comment by mjonuschat** [comment] 2013-07-02 11:05
I guess one of the variables has been defined with an 'em' unit before you include the navbar.scss. Twitter Bootstrap itself only uses 'px' as a base unit. Like the sass compiler says you need to make sure that both variables have an identical/compatible unit (use either px or em).

Since this is not a bug in the gem itself i'm closing this, but feel free to comment if you need further help.

**Closed as completed by mjonuschat** 2013-07-02 11:05 UTC

**Comment by nelsonmariano** [comment] 2013-07-03 12:08
I see...
Well, I'll check it. I'm refactoring the css code of a system that it's already been used, so it can probably be that. I'll try to figure this out.
Thanks again..
