### ISSUE TITLE
Glyphicons are not working in production

### ISSUE THREAD

**Issue by michaelkoper** [mjonuschat/bootstrap-sass-rails#62] opened 2013-10-24 15:17 UTC
In development they are working fine but in production they look like squares. Am I doing something wrong here? Or do I have to manually include them myself?

Im using Rails 4 with bootstrap-sass-rails-3.0.0.3.

**Comment by daniel-illi** [comment] 2013-10-29 09:26
I experience the same problem. 
The hash of the font files referenced in the generated css does not match the hash of the filenames of the font files, so the files can not be found on the server (HTTP 404 Error).

**Comment by michaelkoper** [comment] 2013-10-29 17:16
I dont have time to fix this at this moment so I came with a dirty work around instead :-)

I copied the fonts and put them in the public folder under twitter/bootstrap

I added the url with !important

@font-face
 font-family: 'Glyphicons Halflings'
 src: url("/twitter/bootstrap/glyphiconshalflings-regular.eot") !important
 src: url("/twitter/bootstrap/glyphiconshalflings-regular.eot?#iefix") format('embedded-opentype') !important
 src: url("/twitter/bootstrap/glyphiconshalflings-regular.woff") format('woff') !important
 src: url("/twitter/bootstrap/glyphiconshalflings-regular.ttf") format('truetype') !important
 src: url("/twitter/bootstrap/glyphiconshalflings-regular.svg#glyphicons_halflingsregular") format('svg') !important
 font-weight: normal
 font-style: normal

**Comment by yoyos** [comment] 2013-11-08 08:52
Same issue here.
And I would like to use them in production but rake:precompile generates them with a hash.

**Comment by verdi327** [comment] 2013-11-30 18:37
Experiencing the same issue as well

**Comment by mjonuschat** [comment] 2013-12-02 16:57
Has anybody a sample application that I can put up on Heroku to test this, I can't seem to reproduce this at the moment.

**Comment by mjonuschat** [comment] 2013-12-16 06:39
Since I can't reproduce this I'll close this bug. That the font-files get fingerprinted is normal for the asset pipeline. As the SCSS Files use font-url() the fingerprinted version of the fonts will be used in the combined/compressed CSS output. Please re-open if there is a way to reproduces this.

**Closed as completed by mjonuschat** 2013-12-16 06:39 UTC
